//DELETE http://localhost:8080/messages/4
//Content-Type: application/json

//{"text": "Uppdaterat meddelande!", "author": "Student"}

POST http://localhost:8080/messages
Content-Type: application/json

{"text": "Hej på dig!", "author": "Emil"}